#!/usr/bin/env python
from misc.utility.scons_hints import *

import os

import modules_builders

Import("env")

env_modules = env.Clone()

# Allow modules to detect if they are being built as a module.
env_modules.Append(CPPDEFINES=["GODOT_MODULE"])

Export("env_modules")


# Header with MODULE_*_ENABLED defines.
modules_enabled = env.CommandNoCache(
    "modules_enabled.gen.h", env.Value(env.module_list), env.Run(modules_builders.modules_enabled_builder)
)


register_module_types = env.CommandNoCache(
    "register_module_types.gen.cpp",
    [env.Value(env.modules_detected), modules_enabled],
    env.Run(modules_builders.register_module_types_builder),
)


#Backup & clear paths for this section (building & adding the modules to main binary)
import sys
oldPaths = sys.path

test_headers = []
# libmodule_<name>.a for each active module.
for name, path in env.module_list.items():
    env.modules_sources = []

    #Clear previous module paths and add this module's path so we can import its config file
    sys.path.clear()
    sys.path.insert(0, path)
    import config

    #Check if the config dictates building this module as shared lib
    moduleAsSharedLib = False
    if 'buildAsSharedLib' in dir(config):
        moduleAsSharedLib = config.buildAsSharedLib(env, env["platform"])
        print("Module '", name, "' is flagged as shared library, skipping integration in Godot executable.")    

    # Name for built-in modules, (absolute) path for custom ones.
    base_path = path if os.path.isabs(path) else name
    SConscript(base_path + "/SCsub")

    #If not as a shared lib, build it as per Godot 
    if not moduleAsSharedLib:
        if env.modules_sources:
            lib = env_modules.add_library("module_%s" % name, env.modules_sources)
            env.Prepend(LIBS=[lib])

    if env["tests"]:
        # Lookup potential headers in `tests` subfolder.
        import glob

        module_tests = sorted(glob.glob(os.path.join(base_path, "tests", "*.h")))
        if module_tests != []:
            test_headers += module_tests

    #Un-import the module's config now that we're done with it
    sys.modules.pop("config")

#Restore original paths
sys.path = oldPaths

# Generate header to be included in `tests/test_main.cpp` to run module-specific tests.
if env["tests"]:
    env.Append(CPPDEFINES=["TESTS_ENABLED"])
    env.CommandNoCache("modules_tests.gen.h", test_headers, env.Run(modules_builders.modules_tests_builder))

# libmodules.a with only register_module_types.
# Must be last so that all libmodule_<name>.a libraries are on the right side
# in the linker command.
env.modules_sources = []
env_modules.add_source_files(env.modules_sources, register_module_types)
lib = env_modules.add_library("modules", env.modules_sources)
env.Prepend(LIBS=[lib])
